### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by L0yy** [fcharlie/buna#3]
谢谢你增加了导出函数的功能，但是我发现获取ForwardName的值没实现
我做了如下调整，能添加到您项目中去吗？
在 https://github.com/fcharlie/buna/blob/facb381ee1d2f614d59b7436cb5a05f5d6587188/debug/pe/functions.go#L169 后
添加
`
if exports[i].Address > ds.VirtualAddress && exports[i].Address != 0 {
					exports[i].ForwardName, _ = getString(sdata, int(exports[i].Address-ds.VirtualAddress))
				}
`

**Comment by fcharlie** [comment]
你可以创建一个pr，这样更有参与感。

**Comment by fcharlie** [comment]
已经添加了，你可以使用它
